schema_version = "1.0.0"

id = "snapsplit"
version = "0.1.3"
name = "SnapSplit"
tagline = "Cut and automate connection building for 3D prints."
maintainer = "Christoph Medicus"
contact = "dev@betakontext.de"
website = "https://dev.betakontext.de"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
